# autogenerated by txs
#include:etoolbox
#include:svn-prov
\csname#S
\ClearPostHook#S
\ClearPreHook#S
\PopPostHook#S
\PopPreHook#S
\PushPostHook#S
\PushPreHook#S
\RestorePostHook#S
\RestorePreHook#S
\Rev#S
\SavePostHook#S
\SavePreHook#S
\__hook etoolbox#S
\__hook svn-prov#S
\filebase#S
\fileext#S
\filename#S
\filerev#S
\fileversion#S
\rev#S
\revinfo#S
\unprocessedoptions-etoolbox.sty#S
\unprocessedoptions-svn-prov.sty#S
csnameendcsname#S
etoolbox.sty#S
svn-prov.sty#S
