# autogenerated by txs
#include:CJK
\filedate#S
\fileversion#S
\rubyCJK#S
\rubylatin#S
\rubynooverlap#S
\rubyoverlap#S
\rubysep#S
\rubysize#S
\ruby{arg1}{arg2}#S
CJK.sty#S
\__hook CJK#S
\ruby#S
\unprocessedoptions-CJK.sty#S
csnameendcsname#S
